sample1_file: "/afs/cern.ch/work/r/relhage/private/work/R_Ds/BDT/BDT_Bs/output/Input_tmva_3pi.root"
sample2_file: "/afs/cern.ch/work/r/relhage/private/work/R_Ds/BDT/BDT_Bs/output/Input_tmva_Ds.root"

sample1_label: "MVA 3pi input"
sample2_label: "MVA Ds input"

sample1_tree: "TreeSig_SIG"
sample2_tree: "TreeSig_SIG"

normalize: true

branches:
  B_ETA:
    bins: 150

cuts:
  noCut: ""
  eta_2_5: "B_ETA > 2.0 && B_ETA < 5.0"
  
